<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit052dff74c29040b557409f9af64dbb90
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\HAS\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\HAS\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit052dff74c29040b557409f9af64dbb90::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit052dff74c29040b557409f9af64dbb90::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit052dff74c29040b557409f9af64dbb90::$classMap;

        }, null, ClassLoader::class);
    }
}
