<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf687c17cff0f481f8e019006b201c903
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\HAS\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\HAS\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf687c17cff0f481f8e019006b201c903::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf687c17cff0f481f8e019006b201c903::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf687c17cff0f481f8e019006b201c903::$classMap;

        }, null, ClassLoader::class);
    }
}
