const fontFamilies = {
	Arial: {
		name: 'Arial',
		slug: 'arial',
		family: 'Arial',
		type: 'web',
		fallback: 'sans-serif',
	},
	Helvetica: {
		name: 'Helvetica',
		slug: 'helvetica',
		family: 'Helvetica',
		type: 'web',
		fallback: 'sans-serif',
	},
	'Times New Roman': {
		name: 'Times New Roman',
		slug: 'times-new-roman',
		family: 'Times New Roman',
		type: 'web',
		fallback: 'serif',
	},
	Times: {
		name: 'Times',
		slug: 'times',
		family: 'Times',
		type: 'web',
		fallback: 'serif',
	},
	'Courier New': {
		name: 'Courier New',
		slug: 'courier-new',
		family: 'Courier New',
		type: 'web',
		fallback: 'monospace',
	},
	Courier: {
		name: 'Courier',
		slug: 'courier',
		family: 'Courier',
		type: 'web',
		fallback: 'Courier',
	},
	Verdana: {
		name: 'Verdana',
		slug: 'verdana',
		family: 'Verdana',
		type: 'web',
		fallback: 'sans-serif',
	},
	Georgia: {
		name: 'Georgia',
		slug: 'georgia',
		family: 'Georgia',
		type: 'web',
		fallback: 'serif',
	},
	Palatino: {
		name: 'Palatino',
		slug: 'palatino',
		family: 'Palatino',
		type: 'web',
		fallback: 'serif',
	},
	Garamond: {
		name: 'Garamond',
		slug: 'garamond',
		family: 'Garamond',
		type: 'web',
		fallback: 'serif',
	},
	Bookman: {
		name: 'Bookman',
		slug: 'bookman',
		family: 'Bookman',
		type: 'web',
		fallback: 'serif',
	},
	'Trebuchet MS': {
		name: 'Trebuchet MS',
		slug: 'trebuchet-ms',
		family: 'Trebuchet MS',
		type: 'web',
		fallback: 'sans-serif',
	},
	'Arial Black': {
		name: 'Arial Black',
		slug: 'arial-black',
		family: 'Arial Black',
		type: 'web',
		fallback: 'sans-serif',
	},
	Impact: {
		name: 'Impact',
		slug: 'impact',
		family: 'Impact',
		type: 'web',
		fallback: 'sans-serif',
	},
	Roboto: {
		name: 'Roboto',
		slug: 'roboto',
		family: 'Roboto',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	'Josefin Sans': {
		name: 'Josefin Sans',
		slug: 'josefin-sans',
		family: 'Josefin Sans',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	Karla: {
		name: 'Karla',
		slug: 'karla',
		family: 'Karla',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	Lato: {
		name: 'Lato',
		slug: 'lato',
		family: 'Lato',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	Montserrat: {
		name: 'Montserrat',
		slug: 'montserrat',
		family: 'Montserrat',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	'Open Sans': {
		name: 'Open Sans',
		slug: 'open-sans',
		family: 'Open Sans',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	'Playfair Display': {
		name: 'Playfair Display',
		slug: 'playfair-display',
		family: 'Playfair Display',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	Raleway: {
		name: 'Raleway',
		slug: 'raleway',
		family: 'Raleway',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
	'Source Sans Pro': {
		name: 'Source Sans Pro',
		slug: 'source-sans-pro',
		family: 'Source Sans Pro',
		type: 'google',
		fallback: 'Helvetica, Arial, sans-serif',
	},
};

export default fontFamilies;
