const attributes = {
	uniqueId: 'has-dark-preview',
	showClickToShare: -1,
	showIcon: -1,
	iconSize: 24,
	iconSizeResponsive: {
		mobile: 30,
		tablet: 25,
		desktop: 25,
	},
	customShareText: '',
	shareText: '',
	shareTextInner: [],
	backgroundColor: '#333',
	backgroundColorHover: '#000',
	backgroundColorSync: 'hover',
	backgroundType: 'solid',
	backgroundGradient: '',
	backgroundGradientHover: '',
	backgroundGradientSync: 'normal',
	backgroundImage: {
		url: '',
		id: 0,
		backgroundColor: '#000000',
		backgroundSize: 'cover',
		backgroundPosition: 'center center',
		backgroundRepeat: 'no-repeat',
		backgroundOpacity: 1,
		backgroundOpacityHover: 1,
	},
	icon: '<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="share-alt" class="svg-inline--fa fa-share-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M352 320c-22.608 0-43.387 7.819-59.79 20.895l-102.486-64.054a96.551 96.551 0 0 0 0-41.683l102.486-64.054C308.613 184.181 329.392 192 352 192c53.019 0 96-42.981 96-96S405.019 0 352 0s-96 42.981-96 96c0 7.158.79 14.13 2.276 20.841L155.79 180.895C139.387 167.819 118.608 160 96 160c-53.019 0-96 42.981-96 96s42.981 96 96 96c22.608 0 43.387-7.819 59.79-20.895l102.486 64.054A96.301 96.301 0 0 0 256 416c0 53.019 42.981 96 96 96s96-42.981 96-96-42.981-96-96-96z"></path></svg>',
	iconColor: '#ffffff',
	iconColorHover: '#ffffff',
	iconColorSync: 'sync',
	textColor: '#ffffff',
	textColorHover: '#ffffff',
	textColorSync: 'sync',
	shareTextColor: '#ffffff',
	shareTextColorHover: '#ffffff',
	shareTextColorSync: 'sync',
	fontSize: 24,
	clickShareFontSize: 24,
	clickText: 'Click to Share',
	padding: -1,
	border: -1,
	borderRadius: -1,
	borderColor: '#7b5be6',
	borderColorHover: '#7b5be6',
	borderColorSync: 'sync',
	fontWeight: '400',
	maxWidth: '-1',
	maxWidthUnit: '-1',
	maximumWidth: {
		mobile: {
			width: '95',
			unit: 'vw',
		},
		tablet: {
			width: '95',
			unit: '%',
		},
		desktop: {
			width: '650',
			unit: 'px',
		},
	},
	showClickToShareText: {
		mobile: false,
		tablet: true,
		desktop: true,
	},
	showClickToShareIcon: {
		mobile: true,
		tablet: true,
		desktop: true,
	},
	align: 'center',
	alignment: 'none',
	marginLeft: 0,
	marginRight: 0,
	marginBottom: 0,
	marginTop: -1,
	paddingSize: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '20',
			right: '20',
			bottom: '20',
			left: '20',
			unit: 'px',
			unitSync: true,
		},
	},
	marginSize: {
		mobile: {
			top: '0',
			right: '',
			bottom: '0',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '5',
			right: '',
			bottom: '5',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '20',
			right: 0,
			bottom: '20',
			left: 0,
			unit: 'px',
			unitSync: false,
		},
	},
	borderWidth: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '1',
			right: '1',
			bottom: '1',
			left: '1',
			unit: 'px',
			unitSync: true,
		},
	},
	borderRadiusSize: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '3',
			right: '3',
			bottom: '3',
			left: '3',
			unit: 'px',
			unitSync: true,
		},
	},
	typographyQuote: {
		mobile: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'web',
			fontFallback: '',
		},
		tablet: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'web',
			fontFallback: '',
		},
		desktop: {
			fontFamily: 'Roboto',
			fontFamilySlug: 'roboto',
			fontSize: '26',
			fontSizeUnit: 'px',
			fontWeight: 'normal',
			lineHeight: '1.3',
			lineHeightUnit: 'em',
			textTransform: 'none',
			letterSpacing: '0',
			letterSpacingUnit: 'px',
			fontType: 'google',
			fontFallback: 'Helvetica, Arial, sans-serif',
		},
	},
	typographyShareText: {
		mobile: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'web',
			fontFallback: 'sans-serif',
		},
		tablet: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'web',
			fontFallback: 'sans-serif',
		},
		desktop: {
			fontFamily: 'Lato',
			fontFamilySlug: 'lato',
			fontSize: '28',
			fontSizeUnit: 'px',
			fontWeight: '400',
			lineHeight: '1.3',
			lineHeightUnit: 'em',
			textTransform: 'none',
			letterSpacing: '0',
			letterSpacingUnit: 'px',
			fontType: 'google',
			fontFallback: 'Helvetica, Arial, sans-serif',
		},
	},
};
export { attributes };
