const attributes = {
	uniqueId: 'has-light-preview',
	backgroundColor: '#FFFFFF',
	backgroundColorHover: '#EFEFEF',
	backgroundType: 'solid',
	iconColor: '#333',
	iconColorHover: '#000',
	textColor: '#333',
	textColorHover: '#000',
	shareTextColor: '#333',
	shareTextColorHover: '#000',
	borderColor: '#333',
	borderColorHover: '#000',
	clickText: 'Click to share',
	paddingSize: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '20',
			right: '20',
			bottom: '20',
			left: '20',
			unit: 'px',
			unitSync: true,
		},
	},
	maxWidth: 80,
	marginSize: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '20',
			right: '',
			bottom: '20',
			left: '',
			unit: 'px',
			unitSync: true,
		},
	},
	borderWidth: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '1',
			right: '1',
			bottom: '1',
			left: '1',
			unit: 'px',
			unitSync: true,
		},
	},
	borderRadiusSize: {
		mobile: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		tablet: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			unit: null,
			unitSync: null,
		},
		desktop: {
			top: '4',
			right: '4',
			bottom: '4',
			left: '4',
			unit: 'px',
			unitSync: true,
		},
	},
	typographyQuote: {
		mobile: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontFallback: '',
			fontType: 'web',
		},
		tablet: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontFallback: '',
			fontType: 'web',
		},
		desktop: {
			fontFamily: 'Raleway',
			fontFamilySlug: 'raleway',
			fontSize: '24',
			fontSizeUnit: 'px',
			fontWeight: 'normal',
			lineHeight: '1.3',
			lineHeightUnit: 'em',
			textTransform: 'none',
			letterSpacing: '0',
			letterSpacingUnit: 'px',
			fontFallback: 'serif',
			fontType: 'web',
		},
	},
	typographyShareText: {
		mobile: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'web',
			fontFallback: 'sans-serif',
		},
		tablet: {
			fontFamily: '',
			fontFamilySlug: '',
			fontSize: '',
			fontSizeUnit: 'px',
			fontWeight: '',
			lineHeight: '',
			lineHeightUnit: 'em',
			textTransform: '',
			letterSpacing: '',
			letterSpacingUnit: 'px',
			fontType: 'google',
			fontFallback: 'sans-serif',
		},
		desktop: {
			fontFamily: 'Raleway',
			fontFamilySlug: 'raleway',
			fontSize: '24',
			fontSizeUnit: 'px',
			fontWeight: 'normal',
			lineHeight: '1.3',
			lineHeightUnit: 'em',
			textTransform: 'none',
			letterSpacing: '0',
			letterSpacingUnit: 'px',
			fontType: 'google',
			fontFallback: 'sans-serif',
		},
	},
};
export { attributes };
